### ISSUE TITLE
not possible to style top-level element

### ISSUE THREAD

**Issue by ahdinosaur** [sheetify/sheetify#22]
want to be able to something like:

```js
function render (props) {
  return h('div.' + prefix, {
    textContent: 'hello world!'
  })
}
```

```css
:hover {
  color: green;
}
```

but instead had to do:

```js
function render (props) {
  return h('div.' + prefix, [
    h('div.thing', {
      textContent: 'hello world'
    })
  ])
}
```

```css
.thing:hover {
  color: green;
}
```

ran into this writing: [js](https://github.com/pietgeursen/conway-redux-vdom/blob/master/src/components/cell.js) [css](https://github.com/pietgeursen/conway-redux-vdom/blob/master/src/components/cell.css)

or am i missing something?

**Comment by yoshuawuyts** [comment]
Ah, it took me a while to understand what you're doing. `sheetify` was built with valid CSS in mind; adding namespaces to prevent conflicts after the fact. It seems you've deviated a bit from that.

This might perhaps be a workaround:
```js
// I think ES6 template strings make sense here, but they're always optional
function render (props) {
  return h(`div.${prefix}.thing`, [
    textContent: 'hello world'
  ])
}
```
```css
.thing: { color: green }
.thing:hover { color: blue }
```
Does this make sense / work for you?

**Comment by yoshuawuyts** [comment]
Closing for now, feel free to reopen if this doesn't work for you. I'm trying to be more decisive in issue-control, hah :sparkles:

**Comment by wooorm** [comment]
@yoshuawuyts Are you sure `:hover` at the root is a syntax error / malformed CSS? I’ve always been under the impression that it’s perfectly valid (treated like `*:hover`). Although in the case of this pseudo-class it’s a bit weird though :wink:

**Comment by yoshuawuyts** [comment]
Oh, I meant [the linked example](https://github.com/pietgeursen/conway-redux-vdom/blob/master/src/components/cell.css#L1-L3):
```css
{
  flex: 1;
}
```
I ran it through `csslint` and it had no idea what to do with it. Wasn't aware that `:hover` at the root did that, though I don't think I'd ever write that on purpose to get that behavior (':

**Comment by wooorm** [comment]
Oh sorry, missed that! In that case, you’re def. right!

**Comment by ahdinosaur** [comment]
@yoshuawuyts thanks for the help, the approach for `sheetify` being built for valid CSS is great. :smiley: 

still, the problem with what you suggest is that the css is then prefixed as:

```css
.prefix .thing: { color: green }
.prefix .thing:hover { color: blue }
```

which doesn't match `.prefix.thing` of the element.

here's this change implemented in the example [js](https://github.com/pietgeursen/conway-redux-vdom/blob/fix-sheetify-hack/src/components/cell.js) [css](https://github.com/pietgeursen/conway-redux-vdom/blob/fix-sheetify-hack/src/components/cell.css).

**Comment by hughsk** [comment]
Might this be a candidate for `:host` [as seen here](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/)? Only concern is that it would overload Shadow DOM stuff but that's already happening as a result of the prefixing.

``` css
/* This: */
:host { color: green; }
:host(:hover) { color: blue; }
/* Becomes: */
.prefix { color: green; }
.prefix:hover { color: blue; }
```
